#pragma once

//Error Codes
#define JS_ERROR_NO_MEMORY					1
#define JS_ERROR_CANT_CREATE_MUTEX			2
#define JS_ERROR_BAD_MUTEX					3
#define JS_ERROR_OUT_OF_AVAILABLE_LISCENERS	4
#define ERROR_GENERAL						5
#define JS_ERROR_REINSTANCIATE_SIGLITON		6
#define JS_ERROR_BAD_DIMENSIONS				7
#define JS_ERROR_FAILED_GENERATE_TEXTURE	8
#define JS_ERROR_FRAMEBUFFER_FAILED			9
//Warnings Codes
#define JS_WARNING_LOSSY_EVENTS		1
#define JS_WARNING_UNDEFINED_FILTER 2