#pragma once

//Error Codes
#define JS_ERROR_NO_MEMORY						1
#define JS_ERROR_CANT_CREATE_MUTEX				2
#define JS_ERROR_BAD_MUTEX						3
#define JS_ERROR_OUT_OF_AVAILABLE_LISCENERS		4
#define ERROR_GENERAL							5
#define JS_ERROR_REINSTANCIATE_SIGLITON			6
#define JS_ERROR_BAD_DIMENSIONS					7
#define JS_ERROR_FAILED_GENERATE_TEXTURE		8
#define JS_ERROR_FRAMEBUFFER_FAILED				9
#define JS_ERROR_CANT_CONVERT_PIXELFORMAT		10
#define JS_ERROR_NULL_PARAMETER					11
#define JS_ERROR_SET_PIXELFORMAT_FAILED			12
#define JS_ERROR_FAILED_CREATE_CONTEXT			13
#define JS_ERROR_NOT_SUPPORTED_OPENGL_VERSION	14
#define JS_FATAL_DIRECT3D_CANT_INIT_DEBUG_LAYER 15
#define JS_ERROR_DIRECT3D_ERROR					16
#define JS_ERROR_UNDEFINED_DATA_TYPE			17
#define JS_ERROR_OPENGL_ERROR					18
#define JS_ERROR_NULL_PTR						19
#define JS_ERROR_BAD_GL_PROGRAM					20
#define JS_ERROR_OUT_OF_BOUNDS					21
#define JS_ERROR_BAD_SIZE						22
#define JS_ERROR_SHADER_COMPILE_FAILED			23
#define JS_ERROR_SHADER_LINK_FAILED				24
//Warnings Codes
#define JS_WARNING_LOSSY_EVENTS		1
#define JS_WARNING_UNDEFINED_FILTER 2